- name: Setup cgroup driver
  become: yes
  shell: |
    bash -c 'cat > /etc/docker/daemon.json <<EOF
    {
      "exec-opts": ["native.cgroupdriver=systemd"],
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m"
      },
      "storage-driver": "overlay2"
    }
    EOF'

- name: Restart docker
  become: yes
  service:
    name: docker
    daemon_reload: yes
    state: restarted