- name: Copy the join command to server location
  copy:
    src: join-command
    dest: /home/azureuser/join-command.sh
    mode: 0777

- name: Join the node to cluster
  become: yes
  shell: /home/azureuser/join-command.sh
