apiVersion: v1
kind: Pod
metadata:
  name: gpu-example
spec:
  restartPolicy: Never
  containers:
    - name: gpu-example-1
      image: nvidia/cuda:11.0-base
      command: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
