- name: Install Docker
  hosts: all:!tag_role_wlg
  gather_facts: false
  tasks:
  - import_tasks: tasks/docker_setup.yml
  - import_tasks: tasks/docker_postsetup.yml

- name: Install nvidia-docker
  hosts: tag_role_gpuw
  gather_facts: false
  tasks:
  - import_tasks: tasks/gpuw_setup.yml

- name: Install K8s
  hosts: all:!tag_role_wlg
  gather_facts: true
  tasks:
  - import_tasks: tasks/k8s_presetup.yml
  - import_tasks: tasks/k8s_setup.yml

- name: Setup CP
  hosts: tag_role_cp
  gather_facts: false
  tasks:
  - import_tasks: tasks/cp_setup.yml

- name: Setup CP
  hosts: tag_role_wlg,tag_role_cp
  gather_facts: false
  tasks:
  - import_tasks: tasks/setup_utils.yml

- name: Setup Workers
  hosts: tag_role_cpuw,tag_role_gpuw
  gather_facts: false
  tasks:
  - import_tasks: tasks/worker_setup.yml